[workspace]
members = [
    "converter",
    "compositor",
    "normalizer",
    "renderer",
    "app",
]
resolver = "2"

[workspace.dependencies]
resvg = "0.47"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
wasm-bindgen = "0.2"
image = { version = "0.25", default-features = false, features = ["png"] }
vtracer = "0.6"
serde-keyvalue = "0.1"
