[workspace]
members = [
    "crates/converter",
    "crates/compositor",
    "crates/normalizer",
    "crates/renderer",
    "crates/app",
    "crates/wasm",
]
resolver = "2"

[workspace.dependencies]
resvg = "0.47"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
wasm-bindgen = "0.2"
image = { version = "0.25", default-features = false, features = ["png"] }
vtracer = "0.6"
serde-keyvalue = "0.1"
serde-wasm-bindgen = "0.6"
